# Home Assistant Integration for LEDBrick Scheduler
# Copy this to your Home Assistant configuration.yaml or packages directory

# === Input Helpers ===
# These provide a UI for configuring schedule points

input_number:
  # Time configuration
  ledbrick_schedule_hour:
    name: "Schedule Hour"
    min: 0
    max: 23
    step: 1
    mode: slider
    
  ledbrick_schedule_minute:
    name: "Schedule Minute" 
    min: 0
    max: 59
    step: 1
    mode: slider

  # PWM Channel Values (0-100%)
  ledbrick_pwm_ch1:
    name: "PWM Channel 1"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    
  ledbrick_pwm_ch2:
    name: "PWM Channel 2"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    
  ledbrick_pwm_ch3:
    name: "PWM Channel 3"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    
  ledbrick_pwm_ch4:
    name: "PWM Channel 4"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    
  ledbrick_pwm_ch5:
    name: "PWM Channel 5"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    
  ledbrick_pwm_ch6:
    name: "PWM Channel 6"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    
  ledbrick_pwm_ch7:
    name: "PWM Channel 7"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    
  ledbrick_pwm_ch8:
    name: "PWM Channel 8"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider

  # Current Channel Values (0-2A)
  ledbrick_current_ch1:
    name: "Current Channel 1"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  ledbrick_current_ch2:
    name: "Current Channel 2"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  ledbrick_current_ch3:
    name: "Current Channel 3"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  ledbrick_current_ch4:
    name: "Current Channel 4"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  ledbrick_current_ch5:
    name: "Current Channel 5"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  ledbrick_current_ch6:
    name: "Current Channel 6"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  ledbrick_current_ch7:
    name: "Current Channel 7"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  ledbrick_current_ch8:
    name: "Current Channel 8"
    min: 0
    max: 2
    step: 0.01
    unit_of_measurement: "A"
    mode: slider

input_select:
  # Preset selection
  ledbrick_preset:
    name: "Schedule Preset"
    options:
      - "sunrise_sunset"
      - "full_spectrum"
      - "simple"
      - "custom_1"
      - "custom_2"
    initial: "sunrise_sunset"

input_text:
  # JSON import/export helper
  ledbrick_json_data:
    name: "Schedule JSON Data"
    max: 2048
    multiline: true
    mode: text

input_boolean:
  ledbrick_scheduler_enable:
    name: "Enable LEDBrick Scheduler"
    initial: true

# === Scripts for Easy Configuration ===

script:
  # Set a schedule point using the input helpers
  ledbrick_set_schedule_point:
    alias: "Set LEDBrick Schedule Point"
    sequence:
      - service: esphome.ledbrickplus_set_schedule_point_8ch
        data:
          time_minutes: >
            {{ states('input_number.ledbrick_schedule_hour') | int * 60 + 
               states('input_number.ledbrick_schedule_minute') | int }}
          pwm_ch1: "{{ states('input_number.ledbrick_pwm_ch1') | float }}"
          pwm_ch2: "{{ states('input_number.ledbrick_pwm_ch2') | float }}"
          pwm_ch3: "{{ states('input_number.ledbrick_pwm_ch3') | float }}"
          pwm_ch4: "{{ states('input_number.ledbrick_pwm_ch4') | float }}"
          pwm_ch5: "{{ states('input_number.ledbrick_pwm_ch5') | float }}"
          pwm_ch6: "{{ states('input_number.ledbrick_pwm_ch6') | float }}"
          pwm_ch7: "{{ states('input_number.ledbrick_pwm_ch7') | float }}"
          pwm_ch8: "{{ states('input_number.ledbrick_pwm_ch8') | float }}"
          current_ch1: "{{ states('input_number.ledbrick_current_ch1') | float }}"
          current_ch2: "{{ states('input_number.ledbrick_current_ch2') | float }}"
          current_ch3: "{{ states('input_number.ledbrick_current_ch3') | float }}"
          current_ch4: "{{ states('input_number.ledbrick_current_ch4') | float }}"
          current_ch5: "{{ states('input_number.ledbrick_current_ch5') | float }}"
          current_ch6: "{{ states('input_number.ledbrick_current_ch6') | float }}"
          current_ch7: "{{ states('input_number.ledbrick_current_ch7') | float }}"
          current_ch8: "{{ states('input_number.ledbrick_current_ch8') | float }}"

  # Load selected preset
  ledbrick_load_preset:
    alias: "Load LEDBrick Preset"
    sequence:
      - service: esphome.ledbrickplus_load_preset
        data:
          preset_name: "{{ states('input_select.ledbrick_preset') }}"

  # Quick preset configurations
  ledbrick_morning_gentle:
    alias: "LEDBrick Morning Gentle"
    sequence:
      - service: esphome.ledbrickplus_set_schedule_point_8ch
        data:
          time_minutes: 480  # 8:00 AM
          pwm_ch1: 0
          pwm_ch2: 10
          pwm_ch3: 30
          pwm_ch4: 50
          pwm_ch5: 70
          pwm_ch6: 50
          pwm_ch7: 30
          pwm_ch8: 10
          current_ch1: 0
          current_ch2: 0.2
          current_ch3: 0.5
          current_ch4: 0.8
          current_ch5: 1.2
          current_ch6: 0.8
          current_ch7: 0.5
          current_ch8: 0.2

  ledbrick_midday_full:
    alias: "LEDBrick Midday Full Spectrum"
    sequence:
      - service: esphome.ledbrickplus_set_schedule_point_8ch
        data:
          time_minutes: 720  # 12:00 PM
          pwm_ch1: 60
          pwm_ch2: 80
          pwm_ch3: 100
          pwm_ch4: 100
          pwm_ch5: 100
          pwm_ch6: 100
          pwm_ch7: 80
          pwm_ch8: 60
          current_ch1: 1.0
          current_ch2: 1.5
          current_ch3: 2.0
          current_ch4: 2.0
          current_ch5: 2.0
          current_ch6: 2.0
          current_ch7: 1.5
          current_ch8: 1.0

  ledbrick_evening_warm:
    alias: "LEDBrick Evening Warm"
    sequence:
      - service: esphome.ledbrickplus_set_schedule_point_8ch
        data:
          time_minutes: 1200  # 8:00 PM
          pwm_ch1: 20
          pwm_ch2: 40
          pwm_ch3: 60
          pwm_ch4: 80
          pwm_ch5: 60
          pwm_ch6: 40
          pwm_ch7: 20
          pwm_ch8: 10
          current_ch1: 0.3
          current_ch2: 0.6
          current_ch3: 1.0
          current_ch4: 1.5
          current_ch5: 1.0
          current_ch6: 0.6
          current_ch7: 0.3
          current_ch8: 0.1

  # Control scripts
  ledbrick_enable_scheduler:
    alias: "Enable LEDBrick Scheduler"
    sequence:
      - service: esphome.ledbrickplus_set_scheduler_enabled
        data:
          enabled: true

  ledbrick_disable_scheduler:
    alias: "Disable LEDBrick Scheduler" 
    sequence:
      - service: esphome.ledbrickplus_set_scheduler_enabled
        data:
          enabled: false

  ledbrick_clear_schedule:
    alias: "Clear LEDBrick Schedule"
    sequence:
      - service: esphome.ledbrickplus_clear_schedule

  ledbrick_get_status:
    alias: "Get LEDBrick Status"
    sequence:
      - service: esphome.ledbrickplus_get_scheduler_status

  ledbrick_export_json:
    alias: "Export LEDBrick Schedule JSON"
    sequence:
      - service: esphome.ledbrickplus_get_schedule_json

  ledbrick_import_json:
    alias: "Import LEDBrick Schedule JSON"
    fields:
      json_data:
        name: "JSON Data"
        description: "Complete JSON schedule configuration"
        required: true
        example: '{"timezone":"America/Los_Angeles","enabled":true,"schedule_points":[{"time_minutes":360,"pwm_values":[0,0,0,20,40,60,80,0],"current_values":[0,0,0,0.3,0.6,1.0,1.2,0]}]}'
    sequence:
      - service: esphome.ledbrickplus_import_schedule_json
        data:
          json_data: "{{ json_data }}"

  ledbrick_import_from_input:
    alias: "Import Schedule from Input Text"
    sequence:
      - service: esphome.ledbrickplus_import_schedule_json
        data:
          json_data: "{{ states('input_text.ledbrick_json_data') }}"
      - service: input_text.set_value
        target:
          entity_id: input_text.ledbrick_json_data
        data:
          value: ""  # Clear after import

# === Automations ===

automation:
  # Sync scheduler enable state with input boolean
  - alias: "LEDBrick Scheduler Enable Sync"
    trigger:
      - platform: state
        entity_id: input_boolean.ledbrick_scheduler_enable
    action:
      - service: esphome.ledbrickplus_set_scheduler_enabled
        data:
          enabled: "{{ is_state('input_boolean.ledbrick_scheduler_enable', 'on') }}"

  # Load preset when selection changes
  - alias: "LEDBrick Load Preset on Change"
    trigger:
      - platform: state
        entity_id: input_select.ledbrick_preset
    action:
      - service: esphome.ledbrickplus_load_preset
        data:
          preset_name: "{{ states('input_select.ledbrick_preset') }}"

  # Daily schedule examples
  - alias: "LEDBrick Auto Morning"
    trigger:
      - platform: time
        at: "07:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.ledbrick_scheduler_enable
        state: "on"
    action:
      - service: script.ledbrick_morning_gentle

  - alias: "LEDBrick Auto Midday" 
    trigger:
      - platform: time
        at: "12:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.ledbrick_scheduler_enable
        state: "on"
    action:
      - service: script.ledbrick_midday_full

  - alias: "LEDBrick Auto Evening"
    trigger:
      - platform: time
        at: "20:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.ledbrick_scheduler_enable
        state: "on"
    action:
      - service: script.ledbrick_evening_warm

# === Dashboard Card Configuration ===
# Add this to your Home Assistant Lovelace dashboard

# type: vertical-stack
# cards:
#   - type: entities
#     title: "LEDBrick Scheduler Control"
#     entities:
#       - input_boolean.ledbrick_scheduler_enable
#       - input_select.ledbrick_preset
#       - entity: button.ledbrick_get_status
#         name: "Get Status"
#         tap_action:
#           action: call-service
#           service: script.ledbrick_get_status
#       - entity: button.ledbrick_clear_schedule
#         name: "Clear Schedule"
#         tap_action:
#           action: call-service
#           service: script.ledbrick_clear_schedule
#           
#   - type: entities
#     title: "Schedule Point Configuration"
#     entities:
#       - input_number.ledbrick_schedule_hour
#       - input_number.ledbrick_schedule_minute
#       - entity: button.set_schedule_point
#         name: "Set Schedule Point"
#         tap_action:
#           action: call-service
#           service: script.ledbrick_set_schedule_point
#           
#   - type: entities
#     title: "PWM Values (%)"
#     entities:
#       - input_number.ledbrick_pwm_ch1
#       - input_number.ledbrick_pwm_ch2
#       - input_number.ledbrick_pwm_ch3
#       - input_number.ledbrick_pwm_ch4
#       - input_number.ledbrick_pwm_ch5
#       - input_number.ledbrick_pwm_ch6
#       - input_number.ledbrick_pwm_ch7
#       - input_number.ledbrick_pwm_ch8
#       
#   - type: entities
#     title: "Current Values (A)"
#     entities:
#       - input_number.ledbrick_current_ch1
#       - input_number.ledbrick_current_ch2
#       - input_number.ledbrick_current_ch3
#       - input_number.ledbrick_current_ch4
#       - input_number.ledbrick_current_ch5
#       - input_number.ledbrick_current_ch6
#       - input_number.ledbrick_current_ch7
#       - input_number.ledbrick_current_ch8
#       
#   - type: entities
#     title: "Quick Actions"
#     entities:
#       - entity: script.ledbrick_morning_gentle
#         name: "Morning Gentle"
#       - entity: script.ledbrick_midday_full
#         name: "Midday Full"
#       - entity: script.ledbrick_evening_warm
#         name: "Evening Warm"