#!/usr/bin/env python3
"""Generate components/ledbrick_scheduler/led_models.cpp from lumileds_curves.json.

Run from the firmware directory:
    python3 tools/led_curves/gen_led_models.py

Curves are thinned to keep the table small on the ESP32. A point is dropped only while
linear interpolation between the kept points stays within MAX_ERROR of every original
point, so the firmware's curves match the digitized datasheet curves.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "lumileds_curves.json")
TARGET = os.path.join(HERE, "..", "..", "components", "ledbrick_scheduler", "led_models.cpp")
MAX_ERROR = 0.002  # relative to the value, for output curves; volts for Vf


def interpolate(points, x):
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        if x0 <= x <= x1:
            return y0 + (y1 - y0) * (x - x0) / (x1 - x0) if x1 > x0 else y1
    return points[-1][1] if x > points[-1][0] else points[0][1]


def thin(points, relative):
    """Greedy: extend each segment as far as it stays within MAX_ERROR of the originals."""
    kept = [points[0]]
    i = 0
    while i < len(points) - 1:
        j = len(points) - 1
        while j > i + 1:
            seg = [points[i], points[j]]
            ok = all(abs(interpolate(seg, x) - y) <= (MAX_ERROR * abs(y) if relative else MAX_ERROR)
                     for x, y in points[i:j + 1])
            if ok:
                break
            j -= 1
        kept.append(points[j])
        i = j
    return kept


def flt(value):
    """C++ float literal: 4 significant digits, always with a decimal point (25 -> 25.0f)."""
    text = f"{value:.4g}"
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "f"


def fmt(points, scale_x=1.0):
    return "{" + ", ".join(f"{{{flt(x * scale_x)}, {flt(y)}}}" for x, y in points) + "}"


def main():
    data = json.load(open(SOURCE, encoding="utf-8"))
    out = [
        "// Generated by tools/led_curves/gen_led_models.py from tools/led_curves/lumileds_curves.json.",
        "// Do not edit; change the JSON or the generator and run it again.",
        "#include \"led_dimming.h\"",
        "",
        "namespace ledbrick {",
        "",
        "namespace {",
        "",
        "LedModel make_model(const char* id, const char* name, float test_current_a, float max_current_a,",
        "                    float rth_c_per_w, std::vector<CurvePoint> output_vs_current,",
        "                    std::vector<CurvePoint> output_vs_temp, std::vector<CurvePoint> vf_vs_current) {",
        "    LedModel model;",
        "    model.id = id;",
        "    model.name = name;",
        "    model.test_current_a = test_current_a;",
        "    model.max_current_a = max_current_a;",
        "    model.output_vs_current = std::move(output_vs_current);",
        "    model.curve_temp_c = 85.0f;",
        "    model.output_vs_temp = std::move(output_vs_temp);",
        "    model.rth_c_per_w = rth_c_per_w;",
        "    model.vf_vs_current = std::move(vf_vs_current);",
        "    return model;",
        "}",
        "",
        "}  // namespace",
        "",
        "// " + data["conventions"],
        "const std::vector<LedModel>& builtin_led_models() {",
        "    static const std::vector<LedModel> models = {",
    ]
    total = 0
    for m in data["models"]:
        cur = thin([tuple(p) for p in m["output_vs_current"]["points_mA_rel"]], True)
        temp = thin([tuple(p) for p in m["output_vs_junction_temp"]["points_C_rel"]], True)
        vf = thin([tuple(p) for p in m["vf_vs_current"]["points_mA_V"]], False)
        total += len(cur) + len(temp) + len(vf)
        out += [
            f"        // {m['name']} ({m['part_number']}, BOM {m['bom_code']})",
            f"        //   current: {m['output_vs_current']['source']}",
            f"        //   temperature: {m['output_vs_junction_temp']['source']}",
            f"        //   Vf: {m['vf_vs_current']['source']}",
        ]
        if "note" in m:
            out.append(f"        //   {m['note']}")
        out += [
            f"        make_model(\"{m['id']}\", \"{m['name']}\", {flt(m['test_current_mA'] / 1000)}, "
            f"{flt(m['max_dc_current_mA'] / 1000)}, {flt(m['rth_junction_to_pad_C_per_W'])},",
            f"                   {fmt(cur, 0.001)},",
            f"                   {fmt(temp)},",
            f"                   {fmt(vf, 0.001)}),",
        ]
        print(f"{m['id']:26} current {len(m['output_vs_current']['points_mA_rel'])}->{len(cur)}  "
              f"temp {len(m['output_vs_junction_temp']['points_C_rel'])}->{len(temp)}  "
              f"vf {len(m['vf_vs_current']['points_mA_V'])}->{len(vf)}")
    out += [
        "    };",
        "    return models;",
        "}",
        "",
        "}  // namespace ledbrick",
        "",
    ]
    with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.normpath(TARGET)}: {total} points ({total * 8} bytes of curve data)")


if __name__ == "__main__":
    sys.exit(main())
