# LEDBrick Home Assistant Configuration
# Add these snippets to your configuration.yaml or use as a package

# Input helpers for UI controls
input_number:
  # Quick brightness adjustment
  ledbrick_quick_brightness:
    name: "Quick Brightness"
    min: 0
    max: 100
    step: 5
    unit_of_measurement: "%"
    icon: mdi:brightness-6
    
  # Feeding mode duration
  feeding_duration:
    name: "Feeding Duration"
    min: 5
    max: 30
    step: 5
    unit_of_measurement: "min"
    icon: mdi:timer-sand
    
  # Photography brightness
  photo_brightness:
    name: "Photo Mode Brightness"
    min: 50
    max: 100
    step: 5
    unit_of_measurement: "%"
    icon: mdi:camera

# Moon simulation intensity controls
  moon_blue_intensity:
    name: "Moon Blue Intensity"
    min: 0
    max: 10
    step: 0.5
    unit_of_measurement: "%"
    icon: mdi:moon-waning-crescent
    
  moon_white_intensity:
    name: "Moon White Intensity"
    min: 0
    max: 5
    step: 0.25
    unit_of_measurement: "%"
    icon: mdi:moon-full

input_select:
  # Tank type for different configurations
  tank_type:
    name: "Tank Type"
    options:
      - "Reef"
      - "Planted"
      - "Fish Only"
      - "Coral Propagation"
    icon: mdi:fishbowl
    
  # Lighting modes
  lighting_mode:
    name: "Lighting Mode"
    options:
      - "Schedule"
      - "Manual"
      - "Maintenance"
      - "Photography"
      - "Night Viewing"
    icon: mdi:lightbulb-group
    
  # Power modes
  power_mode:
    name: "Power Mode"
    options:
      - "Normal"
      - "Eco"
      - "Power Saving"
      - "Maximum"
    icon: mdi:lightning-bolt

input_boolean:
  # Feature toggles
  auto_seasonal_adjust:
    name: "Auto Seasonal Adjustment"
    icon: mdi:weather-sunny
    
  storm_mode_enabled:
    name: "Storm Mode"
    icon: mdi:weather-lightning
    
  maintenance_mode:
    name: "Maintenance Mode"
    icon: mdi:wrench
    
  feeding_mode:
    name: "Feeding Mode"
    icon: mdi:fish
    
  night_viewing:
    name: "Night Viewing Mode"
    icon: mdi:moon-waning-crescent

input_text:
  # For storing previous states
  previous_pwm_scale:
    name: "Previous PWM Scale"
    initial: "100"
    
  previous_mode:
    name: "Previous Mode"
    initial: "Schedule"

# Template sensors for calculated values
sensor:
  - platform: template
    sensors:
      # Power consumption estimate (based on current values)
      ledbrick_power_consumption:
        friendly_name: "LEDBrick Power Consumption"
        unit_of_measurement: "W"
        device_class: power
        value_template: >
          {% set voltage = 24 %}
          {% set ch1_current = states('sensor.ledbrickplus_scheduler_current_channel_1') | float(0) %}
          {% set total_current = ch1_current * 8 %}  # Simplified - multiply by channels
          {{ (voltage * total_current) | round(1) }}
      
      # Daily energy consumption
      ledbrick_daily_energy:
        friendly_name: "LEDBrick Daily Energy"
        unit_of_measurement: "kWh"
        device_class: energy
        value_template: >
          {% set power = states('sensor.ledbrick_power_consumption') | float(0) %}
          {{ (power * 24 / 1000) | round(2) }}
      
      # Schedule status
      schedule_status:
        friendly_name: "Schedule Status"
        value_template: >
          {% if is_state('switch.ledbrickplus_scheduler_enabled', 'on') %}
            {% set time = states('sensor.ledbrickplus_scheduler_current_time') %}
            Active ({{ time }})
          {% else %}
            Disabled
          {% endif %}
      
      # Moon phase description
      moon_phase_description:
        friendly_name: "Current Moon Phase"
        value_template: >
          {% set phase = states('sensor.ledbrickplus_moon_phase') | float(0) %}
          {% if phase < 12.5 %}
            🌑 New Moon ({{ phase | round(0) }}%)
          {% elif phase < 37.5 %}
            🌒 Waxing Crescent ({{ phase | round(0) }}%)
          {% elif phase < 62.5 %}
            🌓 First Quarter ({{ phase | round(0) }}%)
          {% elif phase < 87.5 %}
            🌔 Waxing Gibbous ({{ phase | round(0) }}%)
          {% else %}
            🌕 Full Moon ({{ phase | round(0) }}%)
          {% endif %}

# Groups for easier management
group:
  ledbrick_channels:
    name: "LEDBrick Channels"
    entities:
      - light.ledbrickplus_channel_1
      - light.ledbrickplus_channel_2
      - light.ledbrickplus_channel_3
      - light.ledbrickplus_channel_4
      - light.ledbrickplus_channel_5
      - light.ledbrickplus_channel_6
      - light.ledbrickplus_channel_7
      - light.ledbrickplus_channel_8
  
  ledbrick_controls:
    name: "LEDBrick Controls"
    entities:
      - switch.ledbrickplus_scheduler_enabled
      - switch.ledbrickplus_moon_simulation_enabled
      - number.ledbrickplus_pwm_scale
      - input_select.lighting_mode
      - input_select.power_mode

# Custom integrations for advanced features
homeassistant:
  customize:
    # Add custom attributes to entities
    sensor.ledbrickplus_scheduler_pwm_channel_1:
      friendly_name: "Blue Channel"
      icon: mdi:led-on
    sensor.ledbrickplus_scheduler_current_channel_1:
      friendly_name: "Blue Current"
      icon: mdi:current-dc
    number.ledbrickplus_pwm_scale:
      friendly_name: "Global Brightness"
      icon: mdi:brightness-percent