// Generated by tools/led_curves/gen_led_models.py from tools/led_curves/lumileds_curves.json
// and boards/ledbrick-plus/channels.json.
// Do not edit; change the JSON or the generator and run it again.
#include "led_dimming.h"

namespace ledbrick {

namespace {

LedModel make_model(const char* id, const char* name, float test_current_a, float max_current_a,
                    float rth_c_per_w, std::vector<CurvePoint> output_vs_current,
                    std::vector<CurvePoint> output_vs_temp, std::vector<CurvePoint> vf_vs_current) {
    LedModel model;
    model.id = id;
    model.name = name;
    model.test_current_a = test_current_a;
    model.max_current_a = max_current_a;
    model.output_vs_current = std::move(output_vs_current);
    model.curve_temp_c = 85.0f;
    model.output_vs_temp = std::move(output_vs_temp);
    model.rth_c_per_w = rth_c_per_w;
    model.vf_vs_current = std::move(vf_vs_current);
    return model;
}

}  // namespace

// Relative output is 1.0 at the test current (350 mA LUXEON C, 1500 mA Rubix) at Tj = 85 C. Temperature curves are vs junction temperature, 1.0 at 85 C. Digitized from the PDF vector paths (Rubix 2026: raster) and checked against the figures.
const std::vector<LedModel>& builtin_led_models() {
    static const std::vector<LedModel> models = {
        // LUXEON C Royal Blue (L1C1-RYL1000000000, BOM L1C1-RYL)
        //   current: DS144 rev 20250912, Figure 3f, PDF page 16
        //   temperature: DS144 rev 20250912, Figure 2f, PDF page 12
        //   Vf: DS144 rev 20250912, Figure 4e, PDF page 19
        make_model("luxeon_c_royal_blue", "LUXEON C Royal Blue", 0.35f, 1.05f, 2.8f,
                   {{0.105f, 0.331f}, {0.15f, 0.464f}, {0.2f, 0.6055f}, {0.275f, 0.8076f}, {0.35f, 0.9999f}, {0.45f, 1.244f}, {0.575f, 1.533f}, {0.75f, 1.914f}, {0.975f, 2.371f}, {1.05f, 2.517f}},
                   {{25.0f, 1.043f}, {70.0f, 1.014f}, {105.0f, 0.9778f}, {135.0f, 0.9335f}},
                   {{0.1061f, 2.665f}, {0.175f, 2.696f}, {0.325f, 2.743f}, {0.575f, 2.802f}, {1.05f, 2.894f}}),
        // LUXEON C Blue (L1C1-BLU1000000000, BOM L1C1-BLU)
        //   current: DS144 rev 20250912, Figure 3e, PDF page 15
        //   temperature: DS144 rev 20250912, Figure 2e, PDF page 12
        //   Vf: DS144 rev 20250912, Figure 4d, PDF page 18
        make_model("luxeon_c_blue", "LUXEON C Blue", 0.35f, 1.05f, 3.5f,
                   {{0.105f, 0.3535f}, {0.125f, 0.4135f}, {0.15f, 0.486f}, {0.2f, 0.6244f}, {0.25f, 0.7553f}, {0.325f, 0.9407f}, {0.425f, 1.172f}, {0.55f, 1.44f}, {0.7f, 1.74f}, {0.9f, 2.109f}, {1.05f, 2.369f}},
                   {{25.0f, 0.9614f}, {85.0f, 1.0f}, {135.0f, 1.022f}},
                   {{0.105f, 2.756f}, {0.125f, 2.8f}, {0.15f, 2.846f}, {0.175f, 2.887f}, {0.225f, 2.954f}, {0.275f, 3.01f}, {0.35f, 3.08f}, {0.45f, 3.157f}, {0.575f, 3.237f}, {0.725f, 3.319f}, {0.925f, 3.413f}, {1.05f, 3.466f}}),
        // LUXEON C Cyan (L1C1-CYN1000000000, BOM L1C1-CYN)
        //   current: DS144 rev 20250912, Figure 3e, PDF page 15
        //   temperature: DS144 rev 20250912, Figure 2e, PDF page 12
        //   Vf: DS144 rev 20250912, Figure 4d, PDF page 18
        make_model("luxeon_c_cyan", "LUXEON C Cyan", 0.35f, 1.05f, 3.5f,
                   {{0.105f, 0.3974f}, {0.125f, 0.4576f}, {0.15f, 0.5288f}, {0.175f, 0.5964f}, {0.2f, 0.6609f}, {0.25f, 0.782f}, {0.3f, 0.8945f}, {0.375f, 1.05f}, {0.45f, 1.194f}, {0.55f, 1.371f}, {0.675f, 1.573f}, {0.825f, 1.794f}, {1.025f, 2.061f}, {1.05f, 2.092f}},
                   {{25.0f, 1.003f}, {100.0f, 0.9973f}, {130.0f, 0.9844f}, {135.0f, 0.9805f}},
                   {{0.105f, 2.848f}, {0.15f, 2.901f}, {0.2f, 2.948f}, {0.275f, 3.003f}, {0.375f, 3.064f}, {0.525f, 3.14f}, {0.75f, 3.236f}, {1.05f, 3.347f}}),
        // LUXEON C Mint (L1C1-MNT1000000000, BOM L1C1-MNT)
        //   current: DS144 rev 20250912, Figure 3d, PDF page 15
        //   temperature: DS144 rev 20250912, Figure 2d, PDF page 11
        //   Vf: DS144 rev 20250912, Figure 4c, PDF page 18
        make_model("luxeon_c_mint", "LUXEON C Mint", 0.35f, 1.225f, 2.8f,
                   {{0.099f, 0.3161f}, {0.125f, 0.3951f}, {0.15f, 0.4689f}, {0.2f, 0.6106f}, {0.25f, 0.7458f}, {0.325f, 0.9382f}, {0.425f, 1.179f}, {0.55f, 1.46f}, {0.7f, 1.774f}, {0.9f, 2.161f}, {1.15f, 2.607f}, {1.225f, 2.733f}},
                   {{0.0f, 1.087f}, {40.0f, 1.057f}, {70.0f, 1.023f}, {95.0f, 0.9824f}, {115.0f, 0.9401f}, {135.0f, 0.8858f}},
                   {{0.1225f, 2.67f}, {0.225f, 2.712f}, {0.4f, 2.763f}, {0.725f, 2.839f}, {1.225f, 2.938f}}),
        // LUXEON C PC Amber (L1C1-PCA1000000000, BOM L1C1-PCA)
        //   current: DS144 rev 20250912, Figure 3c, PDF page 14
        //   temperature: DS144 rev 20250912, Figure 2c, PDF page 11
        //   Vf: DS144 rev 20250912, Figure 4b, PDF page 17
        make_model("luxeon_c_pc_amber", "LUXEON C PC Amber", 0.35f, 1.05f, 3.0f,
                   {{0.105f, 0.3308f}, {0.125f, 0.3921f}, {0.15f, 0.4668f}, {0.2f, 0.61f}, {0.25f, 0.746f}, {0.325f, 0.9385f}, {0.4f, 1.119f}, {0.5f, 1.346f}, {0.625f, 1.609f}, {0.775f, 1.902f}, {0.975f, 2.26f}, {1.05f, 2.387f}},
                   {{25.0f, 1.157f}, {55.0f, 1.088f}, {80.0f, 1.016f}, {100.0f, 0.9471f}, {120.0f, 0.8657f}},
                   {{0.105f, 2.677f}, {0.2f, 2.711f}, {0.4f, 2.761f}, {0.8f, 2.839f}, {1.05f, 2.883f}}),
        // LUXEON C Deep Red (L1C1-DRD1000000000, BOM L1C1-DRD)
        //   current: DS144 rev 20250912, Figure 3a, PDF page 13
        //   temperature: DS144 rev 20250912, Figure 2a, PDF page 10
        //   Vf: DS144 rev 20250912, Figure 4a, PDF page 17
        make_model("luxeon_c_deep_red", "LUXEON C Deep Red", 0.35f, 0.7f, 2.8f,
                   {{0.07f, 0.2019f}, {0.15f, 0.4355f}, {0.25f, 0.721f}, {0.4f, 1.137f}, {0.625f, 1.741f}, {0.7f, 1.938f}},
                   {{25.0f, 1.104f}, {50.0f, 1.072f}, {70.0f, 1.036f}, {90.0f, 0.9862f}, {105.0f, 0.9378f}, {120.0f, 0.8769f}, {130.0f, 0.8279f}, {135.0f, 0.8004f}},
                   {{0.07f, 1.783f}, {0.125f, 1.823f}, {0.25f, 1.897f}, {0.5f, 2.025f}, {0.7f, 2.121f}}),
        // LUXEON C Violet (L1C1-VLT1000000000, BOM L1C1-VLT)
        //   current: DS144 rev 20250912, Figure 3f, PDF page 16
        //   temperature: DS144 rev 20250912, Figure 2f, PDF page 12
        //   Vf: DS144 rev 20250912, Figure 4c, PDF page 18
        make_model("luxeon_c_violet", "LUXEON C Violet", 0.35f, 1.225f, 3.8f,
                   {{0.1225f, 0.3653f}, {0.175f, 0.5185f}, {0.25f, 0.7298f}, {0.35f, 0.9999f}, {0.475f, 1.322f}, {0.65f, 1.75f}, {0.875f, 2.269f}, {1.15f, 2.867f}, {1.225f, 3.024f}},
                   {{25.0f, 1.083f}, {65.0f, 1.032f}, {100.0f, 0.9732f}, {130.0f, 0.9106f}, {135.0f, 0.8989f}},
                   {{0.1225f, 2.742f}, {0.225f, 2.787f}, {0.425f, 2.853f}, {0.8f, 2.957f}, {1.225f, 3.064f}}),
        // LUXEON C PC Blue (L1C1-PCB1000000000, BOM L1C1-PCB)
        //   current: DS144 rev 20250912, Figure 3e, PDF page 15
        //   temperature: DS144 rev 20250912, Figure 2e, PDF page 12
        //   Vf: DS144 rev 20250912, Figure 4d, PDF page 18
        make_model("luxeon_c_pc_blue", "LUXEON C PC Blue", 0.35f, 1.05f, 3.0f,
                   {{0.105f, 0.3365f}, {0.125f, 0.3967f}, {0.15f, 0.4701f}, {0.2f, 0.6112f}, {0.25f, 0.7459f}, {0.325f, 0.9382f}, {0.425f, 1.18f}, {0.55f, 1.462f}, {0.7f, 1.78f}, {0.9f, 2.173f}, {1.05f, 2.451f}},
                   {{25.0f, 1.036f}, {85.0f, 1.0f}, {135.0f, 0.9575f}},
                   {{0.105f, 2.803f}, {0.125f, 2.838f}, {0.15f, 2.876f}, {0.2f, 2.94f}, {0.275f, 3.016f}, {0.375f, 3.099f}, {0.5f, 3.186f}, {0.675f, 3.291f}, {0.9f, 3.409f}, {1.05f, 3.482f}}),
        // LUXEON C White 5900K (None, BOM L1C1-59)
        //   current: DS144 rev 20250912, Figure 3g, PDF page 16
        //   temperature: DS144 rev 20250912, Figure 2g, PDF page 13
        //   Vf: DS144 rev 20250912, Figure 4f, PDF page 19
        //   DS144 lists no 5900K/3900K part; LUXEON C whites share one set of current, temperature and IV curves, which these use
        make_model("luxeon_c_white_5900k", "LUXEON C White 5900K", 0.35f, 1.225f, 2.8f,
                   {{0.099f, 0.3248f}, {0.125f, 0.4042f}, {0.15f, 0.478f}, {0.2f, 0.6188f}, {0.25f, 0.7519f}, {0.325f, 0.94f}, {0.4f, 1.116f}, {0.5f, 1.337f}, {0.625f, 1.594f}, {0.775f, 1.88f}, {0.975f, 2.231f}, {1.225f, 2.633f}},
                   {{0.0f, 1.069f}, {40.0f, 1.047f}, {70.0f, 1.02f}, {95.0f, 0.9843f}, {115.0f, 0.9444f}, {130.0f, 0.9053f}, {135.0f, 0.8901f}},
                   {{0.1114f, 2.666f}, {0.2f, 2.703f}, {0.375f, 2.757f}, {0.7f, 2.835f}, {1.225f, 2.945f}}),
        // LUXEON C White 3900K (None, BOM L1C1-39)
        //   current: DS144 rev 20250912, Figure 3g, PDF page 16
        //   temperature: DS144 rev 20250912, Figure 2g, PDF page 13
        //   Vf: DS144 rev 20250912, Figure 4f, PDF page 19
        //   DS144 lists no 5900K/3900K part; LUXEON C whites share one set of current, temperature and IV curves, which these use
        make_model("luxeon_c_white_3900k", "LUXEON C White 3900K", 0.35f, 1.225f, 2.8f,
                   {{0.099f, 0.3248f}, {0.125f, 0.4042f}, {0.15f, 0.478f}, {0.2f, 0.6188f}, {0.25f, 0.7519f}, {0.325f, 0.94f}, {0.4f, 1.116f}, {0.5f, 1.337f}, {0.625f, 1.594f}, {0.775f, 1.88f}, {0.975f, 2.231f}, {1.225f, 2.633f}},
                   {{0.0f, 1.069f}, {40.0f, 1.047f}, {70.0f, 1.02f}, {95.0f, 0.9843f}, {115.0f, 0.9444f}, {130.0f, 0.9053f}, {135.0f, 0.8901f}},
                   {{0.1114f, 2.666f}, {0.2f, 2.703f}, {0.375f, 2.757f}, {0.7f, 2.835f}, {1.225f, 2.945f}}),
        // LUXEON Rubix Royal Blue (L1RX-RYL1000000000, BOM L1RX-RYL1000000000)
        //   current: DS309 rev 20260914 Figure 3d below 300 mA (raster); DS309 rev 20230623 Figure 3g from 300 mA (vector)
        //   temperature: DS309 rev 20230623, Figure 2g
        //   Vf: DS309 rev 20230623, Figure 4g
        //   Thermal data from the 2023 revision, which matches the emitter BOM. Max current is the 2026 revision's 1600 mA (the 2023 part allows 3000 mA).
        make_model("luxeon_rubix_royal_blue", "LUXEON Rubix Royal Blue", 1.5f, 1.6f, 4.1f,
                   {{0.1584f, 0.1347f}, {0.175f, 0.1465f}, {0.225f, 0.1873f}, {0.25f, 0.2061f}, {0.275f, 0.227f}, {0.35f, 0.2845f}, {0.45f, 0.3581f}, {0.6f, 0.463f}, {0.75f, 0.5623f}, {0.95f, 0.6875f}, {1.2f, 0.8346f}, {1.5f, 1.0f}, {1.6f, 1.053f}},
                   {{25.0f, 1.081f}, {60.0f, 1.039f}, {90.0f, 0.9909f}, {115.0f, 0.9385f}, {135.0f, 0.8864f}},
                   {{0.3f, 2.849f}, {0.525f, 2.92f}, {0.925f, 3.026f}, {1.625f, 3.188f}, {2.85f, 3.451f}, {3.0f, 3.482f}}),
        // Standard LED (median LUXEON C)
        //   current: median of luxeon_c_royal_blue, luxeon_c_blue, luxeon_c_cyan, luxeon_c_mint, luxeon_c_pc_amber, luxeon_c_violet, luxeon_c_pc_blue, luxeon_c_white_5900k, luxeon_c_white_3900k
        //   temperature: median, as above
        //   Vf: median, as above
        //   Stands in for an LED without a model: a model lost from flash, LEDs with no published curve (the violet string's UV LEDs), and boards without an LED map.
        make_model("standard_led", "Standard LED (median LUXEON C)", 0.35f, 1.25f, 3.0f,
                   {{0.1225f, 0.3892f}, {0.155f, 0.4844f}, {0.205f, 0.6248f}, {0.28f, 0.8244f}, {0.355f, 1.012f}, {0.455f, 1.246f}, {0.58f, 1.517f}, {0.73f, 1.816f}, {0.905f, 2.138f}, {1.25f, 2.726f}},
                   {{25.0f, 1.057f}, {60.0f, 1.03f}, {85.0f, 1.0f}, {105.0f, 0.9659f}, {120.0f, 0.9329f}},
                   {{0.1225f, 2.685f}, {0.23f, 2.72f}, {0.63f, 2.82f}, {1.18f, 2.936f}, {1.25f, 2.95f}}),
    };
    return models;
}

// The LEDs in each channel's string, as built: boards/ledbrick-plus/channels.json
// Other channel counts have no LED map and get one standard LED.
std::vector<LedGroup> default_channel_leds(uint8_t channel, uint8_t num_channels) {
    if (num_channels != 8) {
        return {{STANDARD_LED_MODEL, 1}};
    }
    switch (channel) {
        case 0: return {{"luxeon_c_mint", 4}, {"luxeon_c_cyan", 4}};  // CyMint
        case 1: return {{"luxeon_c_white_5900k", 8}};  // CW
        case 2: return {{"luxeon_c_white_3900k", 4}, {"luxeon_c_pc_amber", 4}};  // WW
        case 3: return {{"luxeon_c_pc_blue", 8}, {"luxeon_c_blue", 4}};  // PCBlue
        case 4: return {{"luxeon_rubix_royal_blue", 13}};  // RBCen
        case 5: return {{"luxeon_c_violet", 6}, {"standard_led", 2}};  // V
        case 6: return {{"luxeon_c_white_5900k", 6}, {"luxeon_c_royal_blue", 4}};  // WBl
        case 7: return {{"luxeon_rubix_royal_blue", 13}};  // RBOuter
        default: return {{STANDARD_LED_MODEL, 1}};
    }
}

}  // namespace ledbrick
