esphome:
  name: ledbrickplus
  friendly_name: ledbrickplus

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ledbrickplus Fallback Hotspot"
    password: "gOqXwag35TIP"

captive_portal:
    
external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/theatrus/mcpwm_unified
      ref: 950020a416ad65383f01da4ed65e16e47769badd
    components: [ mcpwm_unified ]

status_led:
  pin: GPIO1

output:
  - platform: mcpwm_unified
    id: pwm_output_1
    pin: GPIO5
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao1
    pin: GPIO6
    frequency: 500000Hz  
  - platform: mcpwm_unified
    id: pwm_output_2
    pin: GPIO7
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao2
    pin: GPIO8
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_3
    pin: GPIO9
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao3
    pin: GPIO10
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_4
    pin: GPIO11
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao4
    pin: GPIO12
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_5
    pin: GPIO13
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao5
    pin: GPIO14
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_6
    pin: GPIO15
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao6
    pin: GPIO16
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_7
    pin: GPIO17
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao7
    pin: GPIO18
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_8
    pin: GPIO33
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: pwm_output_ao8
    pin: GPIO34
    frequency: 500000Hz
  - platform: mcpwm_unified
    id: fan_pwm
    pin: GPIO37
    frequency: 50000Hz

switch:
  - platform: gpio
    pin: GPIO36
    name: "Fan power"
    id: fan_pwr

fan:
  - platform: speed
    output: fan_pwm
    name: Fan Speed
    id: fan_output


light:
  - platform: monochromatic
    id: lpwm1
    output: pwm_output_1
    name: "Ch1 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur1
    output: pwm_output_ao1
    name: "Ch1 Current"
    gamma_correct: 1
  - platform: monochromatic
    id: lpwm2
    output: pwm_output_2
    name: "Ch2 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur2
    output: pwm_output_ao2
    name: "Ch2 Current"
    gamma_correct: 1
  - platform: monochromatic
    id: lpwm3
    output: pwm_output_3
    name: "Ch3 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur3
    output: pwm_output_ao3
    name: "Ch3 Current"
    gamma_correct: 1
  - platform: monochromatic
    id: lpwm4
    output: pwm_output_4
    name: "Ch4 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur4
    output: pwm_output_ao4
    name: "Ch4 Current"
    gamma_correct: 1
  - platform: monochromatic
    id: lpwm5
    output: pwm_output_5
    name: "Ch5 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur5
    output: pwm_output_ao5
    name: "Ch5 Current"
    gamma_correct: 1
  - platform: monochromatic
    id: lpwm6
    output: pwm_output_6
    name: "Ch6 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur6
    output: pwm_output_ao6
    name: "Ch6 Current"
    gamma_correct: 1
  - platform: monochromatic
    id: lpwm7
    output: pwm_output_7
    name: "Ch7 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur7
    output: pwm_output_ao7
    name: "Ch7 Current"
    gamma_correct: 1
  - platform: monochromatic
    id: lpwm8
    output: pwm_output_8
    name: "Ch8 PWM"
    gamma_correct: 1
  - platform: monochromatic
    id: lcur8
    output: pwm_output_ao8
    name: "Ch8 Current"
    gamma_correct: 1

i2c:
  sda: GPIO3
  scl: GPIO4
  scan: true
  id: bus_a

sensor:
  - platform: ina2xx_i2c
    id: current_sensor
    model: INA228
    address: 0x40
    shunt_resistance: 0.005 ohm
    max_current: 20 A
    adc_range: 0
    update_interval: 5s
    current: "INA228 Current"
    bus_voltage: "INA228 Bus Voltage"
    charge: "INA228 Charge"

  - platform: pulse_counter
    pin: 
      number: GPIO35
      mode: INPUT
    unit_of_measurement: 'RPM'
    id: fan_speed
    name: Fan Speed
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
