esphome:
  name: test-scheduler
  friendly_name: "LEDBrick Scheduler Test"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  services:
    - service: test_service
      then:
        - logger.log: "Test service called"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# External components
external_components:
  - source:
      type: local
      path: components
    components: [ ledbrick_scheduler ]

# Time synchronization
time:
  - platform: sntp
    id: sntp_time
    servers:
      - pool.ntp.org

# Test our custom scheduler component
ledbrick_scheduler:
  id: main_scheduler
  channels: 2  # Test with just 2 channels
  update_interval: 10s  # Faster for testing
  time_source: sntp_time

# Test PWM outputs
output:
  - platform: ledc
    pin: GPIO5
    id: pwm_output_1
    frequency: 1000Hz
  - platform: ledc
    pin: GPIO7
    id: pwm_output_2
    frequency: 1000Hz

# Test current control numbers
number:
  - platform: template
    id: current_1
    name: "Channel 1 Current"
    optimistic: true
    min_value: 0.0
    max_value: 2.0
    step: 0.01
    unit_of_measurement: "A"
    mode: slider
    
  - platform: template
    id: current_2
    name: "Channel 2 Current"
    optimistic: true
    min_value: 0.0
    max_value: 2.0
    step: 0.01
    unit_of_measurement: "A"
    mode: slider

  - platform: template
    id: max_current_1
    name: "Channel 1 Max Current"
    optimistic: true
    min_value: 0.0
    max_value: 2.0
    step: 0.01
    initial_value: 1.5
    unit_of_measurement: "A"
    mode: slider
    entity_category: config
    
  - platform: template
    id: max_current_2
    name: "Channel 2 Max Current"
    optimistic: true
    min_value: 0.0
    max_value: 2.0
    step: 0.01
    initial_value: 1.5
    unit_of_measurement: "A"
    mode: slider
    entity_category: config

# Connect scheduler to outputs (this would need additional code)
# For now we'll test the basic component compilation