name: ESPHome Build

on:
  push:
    branches: [ master, main ]
    paths: [ 'firmware/**' ]
  pull_request:
    branches: [ master, main ]
    paths: [ 'firmware/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ESPHome firmware
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Build ESPHome Binary
      uses: esphome/build-action@v6
      id: esphome-build
      with:
        yaml-file: firmware/ledbrick-plus.yaml
        version: 'latest'
      env:
        # Mock secrets for compilation - valid format required for build
        SECRETS_api_encryption_key: "0InzFsPpuTBIm6B6HVhVupBRBwBTY2oT3fRnc3JATdM="
        SECRETS_ota_password: "mock_ota_password"
        SECRETS_wifi_ssid: "MockWiFi"
        SECRETS_wifi_password: "mock_password"